submitit WARNING (2023-09-16 23:41:38,065) - Bypassing signal SIGCONT
submitit WARNING (2023-09-16 23:41:38,066) - Caught signal SIGUSR2 on worker3164: this job is timed-out.
submitit ERROR (2023-09-16 23:41:38,232) - Submitted job triggered an exception
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
             ^^^^^^^^^^^^^^^^
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/supplementary-xt_approximation.py", line 44, in generate_samples
    samples_seq_reverse = sequential_posterior_sampler(prior_sampler, manifold_initial_point, M, likelihood_sigma, s, num_cycles=sample_size, eval_at_mean=eval_at_mean, device=device)[1]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/utils/likelihood_utils.py", line 338, in sequential_posterior_sampler
    cur_z, z_forward, z_reverse = sequential_posterior_cycle(cur_z, prior_sampler, Mm, sigma, s, n_steps, alphas, betas, one_minus_alphas_bar_sqrt, eval_at_mean, device)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/utils/likelihood_utils.py", line 304, in sequential_posterior_cycle
    cur_z = posterior_sample_occlusion(prior_sampler, t, cur_z, Mm, sigma, s, n_steps, alphas,betas,one_minus_alphas_bar_sqrt, eval_at_mean, device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/utils/likelihood_utils.py", line 227, in posterior_sample_occlusion
    eps_theta = prior_sampler(z, T)
                ^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/models.py", line 341, in forward
    out = self.features(x, t)
          ^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/models.py", line 185, in forward
    inputs = module(inputs, t)
             ^^^^^^^^^^^^^^^^^
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/ceph/users/blyo1/projects/LyoSavin2023/core/models.py", line 234, in forward
    t = t.repeat_interleave(self.num_out, 1).view(batch_size, -1, 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/blyo1/ceph/envs/pyenv311/lib/python3.11/site-packages/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out and not checkpointable.
srun: error: worker3164: task 0: Exited with exit code 1
